name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag grafana:latest
    - name: Export docker 
      run: docker save -o grafana_latest.tar grafana:latest
      
    - name: Upload COS
      uses: zkqiang/tencent-cos-action@v0.1.0
      with:
        args: upload -r grafana_latest.tar /worker/docker/grafana/  
        secret_id: ${{ secrets.SECRET_ID }}
        secret_key: ${{ secrets.SECRET_KEY }}
        bucket: ${{ secrets.BUCKET }}
        region: ${{ secrets.REGION }}
