name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag grafana:$(date +%s)
      
    - name: Upload COS
      uses: zkqiang/tencent-cos-action@v0.1.0
      with:
        args: delete -r -f /worker/docker/grafana/ && upload -r ./dist/ /worker/docker/grafana/  
        secret_id: ${{ secrets.SECRET_ID }}
        secret_key: ${{ secrets.SECRET_KEY }}
        bucket: ${{ secrets.BUCKET }}
        region: ${{ secrets.REGION }}
